services:
  # api:
  #   build: .
  #   ports: ["8000:8000"]
  #   environment:
  #     MLFLOW_TRACKING_URI: http://mlflow:5000
  #     MLFLOW_S3_ENDPOINT_URL: http://minio:9000   # чтобы читать артефакты
  #     AWS_ACCESS_KEY_ID: admin                    #   модели из MinIO
  #     AWS_SECRET_ACCESS_KEY: admin123
  #   depends_on: [mlflow]

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin123
    command: >
      mlflow server --host 0.0.0.0
        --allowed-hosts mlflow:5000,mlflow,api,localhost,localhost:5000,127.0.0.1
        --backend-store-uri sqlite:///mlflow.db
        --artifacts-destination s3://mlflow/
    ports: ["5000:5000"]
    depends_on: [minio]

  minio:
    image: minio/minio
    command: server /data --console-address ':9001'
    ports: ["9000:9000", "9001:9001"]
    environment: { MINIO_ROOT_USER: admin, MINIO_ROOT_PASSWORD: admin123 }
    volumes: ["minio-data:/data"]

volumes:
  minio-data:
