apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-api
spec:
  selector:
    matchLabels:
      app: churn-api
  template:
    metadata:
      labels:
        app: churn-api
    spec:
      containers:
      - name: churn-api
        image: ghcr.io/yancharskaya/churn-service:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: churn-svc
spec:
  type: LoadBalancer
  selector:
    app: churn-api
  ports:
  - port: 3000
    targetPort: 8000
