name: ci
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.14' }
      - run: pip install ruff
      - run: ruff check src/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.14'
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'
      - run: pip install -r requirements-dev.txt
      - run: python train/train.py
      - run: pytest tests/ -v
      
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.pkl

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions: { packages: write, contents: write }
    steps:
      - uses: actions/checkout@v4

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: .

      # Генерируем новую версию (только при пуше/мерже в main)
      - name: Bump version and push Git tag
        id: tag_version
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch # По умолчанию увеличивает последнюю цифру (v1.0.0 -> v1.0.1)

      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |            
            # 1. хэш (например: 8c34f21)
            type=sha,format=short
            
            # 2. latest
            type=raw,value=latest

            # 3. tag релиза из github
            type=raw,value=${{ steps.tag_version.outputs.new_tag }},enable=${{ steps.tag_version.outputs.new_tag != '' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }} 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Включаем кеширование слоев Docker
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Создаем автоматический релиз в GitHub (только для main)
      - name: Create a GitHub release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          generateReleaseNotes: true